/**
 * Carbon icon compatibility layer.
 *
 * The original application imported Lucide names directly in more than one
 * hundred components. Keeping the familiar local names lets us migrate the
 * complete icon surface in one reviewable step while every rendered glyph now
 * comes from IBM Carbon's official icon package.
 */
import type { CarbonIconType } from '@carbon/icons-react/lib/CarbonIcon';
import {
  Activity as CarbonActivity,
  Add,
  MagicWand,
  Anchor,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Attachment,
  Blog,
  Book,
  Bookmark,
  Box as CarbonBox,
  Building as CarbonBuilding,
  Calendar as CarbonCalendar,
  CalendarHeatMap,
  CalendarTools,
  Car as CarbonCar,
  Catalog,
  Certificate,
  CertificateCheck,
  ChartBar,
  ChartLine,
  Chat,
  Checkmark,
  CheckmarkFilled,
  CheckboxChecked,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Chip,
  Close,
  CloudUpload,
  Compass,
  Copy,
  CopyToClipboard,
  CurrencyDollar,
  Dashboard,
  DataTable,
  DeliveryTruck,
  DevicesApps,
  Document,
  DocumentDownload,
  Download,
  Earth,
  Edit,
  Education,
  Email,
  Favorite,
  Filter,
  FlowConnection,
  Folder,
  FolderTree,
  Gift,
  Globe,
  Grid,
  Group,
  Hashtag,
  Headphones,
  HealthCross,
  Help,
  Home,
  Humidity,
  IbmDb2Warehouse,
  Image,
  Industry,
  Information,
  InProgress,
  Key,
  Launch,
  Layers,
  Lightning,
  Link,
  List,
  ListBoxes,
  ListChecked,
  Location,
  Locked,
  LogoFacebook,
  LogoLinkedin,
  LogoX,
  LogoYoutube,
  Logout,
  Maximize,
  Menu,
  Package,
  Partnership,
  Phone,
  PhoneOutgoing,
  Pills,
  Plane,
  Portfolio,
  Printer,
  Recycle,
  Renew,
  Reset,
  Restaurant,
  Ruler,
  Save,
  Scale,
  Search,
  Security,
  Send,
  Settings,
  SettingsAdjust,
  Share,
  ShipmentDelivery,
  ShoppingBag,
  ShoppingCart,
  Star,
  Subtract,
  Sun,
  Sustainability,
  Tag,
  Target,
  TaskComplete,
  Temperature,
  ThumbsDown,
  ThumbsUp,
  Time,
  Tools,
  TrashCan,
  Upload,
  User,
  UserAvatar,
  UserCertification,
  View,
  ViewOff,
  Warning,
  WarningAlt,
  Windy,
  ZoomIn
} from '@carbon/icons-react';

export type LucideIcon = CarbonIconType;

export {
  Add as Plus,
  Add as PlusCircle,
  MagicWand as Sparkles,
  Anchor,
  Archive,
  ArrowDown as ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Attachment as Paperclip,
  Blog as Newspaper,
  Book as BookOpen,
  Bookmark,
  CarbonActivity as Activity,
  CarbonBox as Box,
  CarbonBox as BoxSelect,
  CarbonBuilding as Building,
  CarbonBuilding as Building2,
  CarbonCalendar as Calendar,
  CarbonCalendar as CalendarDays,
  CarbonCar as Car,
  CalendarHeatMap as CalendarRange,
  CalendarTools as CalendarClock,
  CalendarTools as Clock3,
  Catalog as Armchair,
  Certificate as Award,
  CertificateCheck as BadgeCheck,
  ChartBar as BarChart2,
  ChartLine as TrendingDown,
  ChartLine as TrendingUp,
  Chat as MessageSquare,
  Checkmark as Check,
  CheckmarkFilled as CheckCircle,
  CheckmarkFilled as CheckCircle2,
  CheckboxChecked as CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Chip as Cpu,
  Close as X,
  Close as XCircle,
  CloudUpload as UploadCloud,
  Compass as Navigation,
  Copy,
  CopyToClipboard as ClipboardCheck,
  CurrencyDollar as CreditCard,
  CurrencyDollar as DollarSign,
  Dashboard as LayoutDashboard,
  DataTable as FileSpreadsheet,
  DeliveryTruck as Truck,
  DevicesApps as MonitorSmartphone,
  Document as FileBox,
  Document as FileText,
  DocumentDownload as FileDown,
  Download,
  Earth as Globe2,
  Edit,
  Edit as Edit2,
  Edit as Edit3,
  Education as GraduationCap,
  Email as Mail,
  Favorite as Heart,
  Filter,
  FlowConnection as Route,
  Folder,
  FolderTree,
  Gift,
  Globe,
  Grid as LayoutGrid,
  Group as Users,
  Group as Users2,
  Hashtag as Hash,
  Headphones,
  HealthCross as HeartPulse,
  Help as HelpCircle,
  Home,
  Humidity as Droplets,
  IbmDb2Warehouse as Warehouse,
  Image,
  Industry as Factory,
  Information as Info,
  InProgress as Loader2,
  Key as KeyRound,
  Launch as ExternalLink,
  Layers,
  Lightning as Zap,
  Link as Link2,
  List,
  ListBoxes as Boxes,
  ListChecked as ClipboardList,
  ListChecked as ListChecks,
  Location as MapPin,
  Locked as Lock,
  LogoFacebook,
  LogoLinkedin,
  LogoX,
  LogoYoutube,
  Logout as LogOut,
  Maximize as Maximize2,
  Menu,
  Package,
  Package as PackageCheck,
  Partnership as HeartHandshake,
  Phone,
  PhoneOutgoing as PhoneCall,
  Pills as Pill,
  Plane,
  Portfolio as Briefcase,
  Printer,
  Recycle,
  Renew as RefreshCw,
  Renew as RotateCcw,
  Renew as RotateCw,
  Reset as Sliders,
  Restaurant as Utensils,
  Ruler,
  Save,
  Scale,
  Search,
  Security as Shield,
  Security as ShieldAlert,
  Security as ShieldCheck,
  Security,
  Send,
  Settings,
  SettingsAdjust as Settings2,
  SettingsAdjust as SlidersHorizontal,
  Share as Share2,
  ShipmentDelivery as Ship,
  ShoppingBag,
  ShoppingCart,
  Star,
  Subtract as Minus,
  Sun,
  Sustainability as Leaf,
  Tag,
  Target,
  TaskComplete as FileCheck,
  Temperature as Thermometer,
  ThumbsDown,
  ThumbsUp,
  Time as Clock,
  Tools as Wrench,
  TrashCan as Trash,
  TrashCan as Trash2,
  Upload,
  User,
  UserAvatar as UserRound,
  UserCertification as UserCheck,
  View as Eye,
  ViewOff as EyeOff,
  Warning as AlertTriangle,
  WarningAlt as AlertCircle,
  Windy as Wind,
  ZoomIn
};
