import { TRANSLATION_RELATION_DEFS } from '../lib/i18n.mjs';

export const RELATION_DEFS = [
  { collection: 'product_categories', field: 'parent', related_collection: 'product_categories' },
  { collection: 'products', field: 'category', related_collection: 'product_categories' },
  { collection: 'product_skus', field: 'product', related_collection: 'products', meta: { one_field: 'skus' } },
  { collection: 'products_product_attributes', field: 'products_id', related_collection: 'products', meta: { one_field: 'assigned_attributes', junction_field: 'product_attributes_id' } },
  { collection: 'products_product_attributes', field: 'product_attributes_id', related_collection: 'product_attributes', meta: { junction_field: 'products_id' } },
  { collection: 'product_attribute_options', field: 'attribute', related_collection: 'product_attributes', meta: { one_field: 'options' } },
  { collection: 'documents', field: 'product', related_collection: 'products', meta: { one_field: 'documents' } },
  { collection: 'documents', field: 'file', related_collection: 'directus_files', schema: { on_delete: 'SET NULL' } },
  { collection: 'iso_certifications', field: 'file', related_collection: 'directus_files', schema: { on_delete: 'SET NULL' } },
  { collection: 'case_studies', field: 'industry', related_collection: 'industries' },
  { collection: 'customers', field: 'user', related_collection: 'directus_users' },
  { collection: 'customers', field: 'sales_owner', related_collection: 'directus_users' },
  { collection: 'orders', field: 'customer', related_collection: 'customers', meta: { one_field: 'orders' } },
  { collection: 'orders', field: 'hub', related_collection: 'regional_hubs' },
  { collection: 'regional_hubs', field: 'province', related_collection: 'vn_provinces' },
  { collection: 'hub_industrial_zones', field: 'hub', related_collection: 'regional_hubs', meta: { one_field: 'industrial_zones' } },
  { collection: 'hub_industrial_zones', field: 'image', related_collection: 'directus_files', schema: { on_delete: 'SET NULL' } },
  { collection: 'hub_team_members', field: 'hub', related_collection: 'regional_hubs', meta: { one_field: 'team_members' } },
  { collection: 'hub_team_members', field: 'photo', related_collection: 'directus_files', schema: { on_delete: 'SET NULL' } },
  { collection: 'order_items', field: 'order', related_collection: 'orders', meta: { one_field: 'items' } },
  { collection: 'order_items', field: 'sku', related_collection: 'product_skus' },
  { collection: 'invoices', field: 'customer', related_collection: 'customers', meta: { one_field: 'invoices' } },
  { collection: 'invoices', field: 'order', related_collection: 'orders' },
  { collection: 'deliveries', field: 'order', related_collection: 'orders', meta: { one_field: 'deliveries' } },
  { collection: 'deliveries', field: 'hub', related_collection: 'regional_hubs' },
  { collection: 'rfq_requests', field: 'hub', related_collection: 'regional_hubs' },
  { collection: 'rfq_requests', field: 'assigned_sales', related_collection: 'directus_users' },
  { collection: 'rfq_requests', field: 'user', related_collection: 'directus_users' },
  { collection: 'rfq_assignment_rules', field: 'hub', related_collection: 'regional_hubs' },
  { collection: 'rfq_assignment_rules', field: 'industry', related_collection: 'industries' },
  { collection: 'rfq_assignment_rules', field: 'assigned_sales', related_collection: 'directus_users' },
  { collection: 'products_industries', field: 'products_id', related_collection: 'products', meta: { one_field: 'industries' } },
  { collection: 'products_industries', field: 'industries_id', related_collection: 'industries' },
  { collection: 'products_files', field: 'products_id', related_collection: 'products', meta: { one_field: 'gallery' } },
  { collection: 'products_files', field: 'directus_files_id', related_collection: 'directus_files', schema: { on_delete: 'CASCADE' } },
  { collection: 'products_standards', field: 'products_id', related_collection: 'products', meta: { one_field: 'standards' } },
  { collection: 'products_standards', field: 'standards_id', related_collection: 'standards' },
  { collection: 'products_regional_hubs', field: 'products_id', related_collection: 'products', meta: { one_field: 'regions', junction_field: 'regional_hubs_id' } },
  { collection: 'products_regional_hubs', field: 'regional_hubs_id', related_collection: 'regional_hubs', meta: { junction_field: 'products_id' } },
  { collection: 'sample_requests', field: 'user', related_collection: 'directus_users' },
  { collection: 'media_retention', field: 'file', related_collection: 'directus_files', schema: { on_delete: 'CASCADE' } },
  { collection: 'media_retention', field: 'deleted_by', related_collection: 'directus_users' },
  { collection: 'media_retention', field: 'hard_deleted_by', related_collection: 'directus_users' },
  { collection: 'media_audit_events', field: 'actor', related_collection: 'directus_users' },
  ...TRANSLATION_RELATION_DEFS
];
